### ISSUE TITLE
Missing files on 4.1.3

### ISSUE THREAD

**Issue by ricardobarone** [webjars/angular-file-upload#32]
The following files are missing:
 * ng-file-upload.js
 * ng-file-upload.min.js
 * ng-file-upload-shim.js
 * ng-file-upload-shim.min.js

**Comment by ricardobarone** [comment]
Actually, the github project name has also changed to `ng-file-upload`.

The `pom.xml` should be updated to this new location or maybe it's better to just create a new webjar package for `ng-file-upload`?

**Comment by jamesward** [comment]
Those files seem to be there: http://www.webjars.org/listfiles/angular-file-upload/4.1.3

We can create a new WebJar for this but in the long run it might be better to use a Bower WebJar for this.

**Comment by ricardobarone** [comment]
My mistake about the files... thanks for the quick response!
